[phases.setup]
nixPkgs = ["nodejs_20", "npm-9_x"]

[phases.install]
cmds = ["npm install", "npm install --prefix client", "npm install --prefix server"]

[phases.build]
cmds = ["npm run build --prefix client"]

[start]
cmd = "NODE_ENV=production node server/src/index.js"
